dna = input("Введите последовательность ДНК: ")

print("=== Анализ последовательности ДНК ===\n")
print(f"Введите последовательность ДНК: {dna}")
dna = dna.upper()
print(f"Последовательность в верхнем регистре: {dna}")
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
print("Подсчёт нуклеотидов:")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
x = len(dna)
print(f"Общая длина: {x} нуклеотидов")